const students = {
    "khongtien": { displayName: "Khổng Tiến", img: "/assets/images/khongtien.jpg", fullName: "Khổng Mạnh Tiến", dob: "12/03/2010" },
    "caoson": { displayName: "Cao Sơn", img: "/assets/images/caoson.jpg", fullName: "Tạ Cao Sơn", dob: "25/12/2010" },
    "dangkhoi": { displayName: "Đăng Khôi", img: "/assets/images/dangkhoi.jpg", role: "XUNG KÍCH", fullName: "Phạm Đăng Khôi", dob: "07/04/2010" },
    "minhson": { displayName: "Minh Sơn", img: "/assets/images/minhson.jpg", fullName: "Đoàn Minh Sơn", role: "Lớp phó lao động", dob: "11/11/2010" },
    "lenam": { displayName: "Lê Nam", img: "/assets/images/lenam.jpg", fullName: "Lê Bảo Nam", dob: "23/10/2010" },
    "huuchuong": { displayName: "Hữu Chương", img: "/assets/images/huuchuong.jpg", fullName: "Nguyễn Hữu Chương", dob: "12/02/2010" },
    "nguyenhuy": { displayName: "Nguyễn Huy", img: "/assets/images/nguyenhuy.jpg", fullName: "Nguyễn Gia Huy", dob: "17/02/2010" },
    "viethoang": { displayName: "Việt Hoàng", img: "/assets/images/viethoang.jpg", fullName: "Đỗ Việt Hoàng", dob: "02/03/2010" },
    "tiendat": { displayName: "Tiến Đạt", img: "/assets/images/tiendat.jpg", fullName: "Trần Tiến Đạt", dob: "16/06/2010" },
    "duyanh": { displayName: "Duy Anh", img: "/assets/images/duyanh.jpg", fullName: "Ngô Duy Anh", dob: "25/10/2010" },
    "viettrung": { displayName: "Việt Trung", img: "/assets/images/viettrung.jpg", fullName: "Hoàng Việt Trung", dob: "23/03/2010" },
    "hoangha": { displayName: "Hoàng Hà", img: "/assets/images/hoangha.jpg", fullName: "Phạm Hoàng Hà", dob: "23/03/2010" },
    "doankhanh": { displayName: "Đoàn Khánh", img: "/assets/images/doankhanh.jpg", fullName: "Đoàn Nam Khánh", dob: "06/05/2010" },
    "phamnam": { displayName: "Phạm Nam", img: "/assets/images/phamnam.jpg", role: "Cờ đỏ", fullName: "Phạm Bảo Nam", dob: "28/12/2010" },
    "ducanh": { displayName: "Đức Anh", img: "/assets/images/ducanh.jpg", fullName: "Lê Đức Anh", dob: "15/05/2010" },
    "npanh": { displayName: "Nguyễn P.Anh", img: "/assets/images/npa.jpg", fullName: "Nguyễn Phương Anh", dob: "17/07/2010" },
    "ngnamkhanh": { displayName: "Nguyễn Khánh", img: "/assets/images/ngkhanh.jpg", fullName: "Nguyễn Nam Khánh", dob: "11/05/2010" },
    "thuyduong": { displayName: "Thùy Dương", img: "/assets/images/thuyduong.jpg", fullName: "Hoàng Thùy Dương", dob: "10/02/2010" },
    "vinhhung": { displayName: "Vĩnh Hưng", img: "/assets/images/vinhhung.jpg", role: "Tổ trưởng Tổ 3", fullName: "Trần Vĩnh Hưng", dob: "04/08/2010" },
    "haininh": { displayName: "Hải Ninh", img: "/assets/images/haininh.jpg", fullName: "Thân Thị Hải Ninh", dob: "04/01/2010" },
    "khanhhuyen": { displayName: "Khánh Huyền", img: "/assets/images/khanhhuyen.jpg", role: "Tổ trưởng Tổ 1", fullName: "Nguyễn Khánh Huyền", dob: "06/11/2010" },
    "minhtien": { displayName: "Minh Tiến", img: "/assets/images/minhtien.jpg", fullName: "Nguyễn Minh Tiến", dob: "13/01/2010" },
    "manhduy": { displayName: "Mạnh Duy", img: "/assets/images/manhduy.jpg", role: "XUNG KÍCH", fullName: "Nguyễn Mạnh Duy", dob: "29/09/2010" },
    "haily": { displayName: "Hải Ly", img: "/assets/images/haily.jpg", role: "Tổ trưởng Tổ 2", fullName: "Hoàng Hải Ly", dob: "16/04/2010" },
    "thaoanh": { displayName: "Thảo Anh", img: "/assets/images/thaoanh.jpg", fullName: "Nguyễn Hoàng Thảo Anh", dob: "29/07/2010" },
    "hoangthao": { displayName: "Hoàng Thảo", img: "/assets/images/hoangthao.jpg", fullName: "Hoàng Thị Hương Thảo", dob: "12/11/2010" },
    "nguyenthao": { displayName: "Nguyễn Thảo", img: "/assets/images/nguyenthao.jpg", fullName: "Nguyễn Phương Thảo", dob: "25/02/2010" },
    "tancuong": { displayName: "Tân Cương", img: "/assets/images/tancuong.jpg", fullName: "Vũ Tân Cương", dob: "21/06/2010" },
    "ngochan": { displayName: "Ngọc Hân", img: "/assets/images/ngochan.jpg", fullName: "Vy Ngọc Hân", dob: "18/11/2010" },
    "baouyen": { displayName: "Bảo Uyên", img: "/assets/images/baouyen.jpg", fullName: "Nguyễn Bảo Uyên", dob: "19/06/2010" },
    "viettrinh": { displayName: "Việt Trinh", img: "/assets/images/viettrinh.jpg", fullName: "Vy Việt Trinh", dob: "12/11/2010" },
    "baongoc": { displayName: "Bảo Ngọc", img: "/assets/images/baongoc.jpg", role: "Cờ đỏ", fullName: "Vi Bảo Ngọc", dob: "06/02/2010" },
    "khanhan": { displayName: "Khánh An", img: "/assets/images/khanhan.jpg", fullName: "Vũ Huy Khánh An", dob: "01/12/2010" },
    "baoyen": { displayName: "Bảo Yến", img: "/assets/images/baoyen.jpg", role: "Bí Thư", fullName: "Trần Bảo Yến", dob: "10/02/2010" },
    "thienphu": { displayName: "Thiện Phú", img: "/assets/images/thienphu.jpg", fullName: "Trần Thiện Phú", role:"Lớp phó văn thể", dob: "03/02/2010" },
    "nhatanh": { displayName: "Nhật Anh", img: "/assets/images/nhatanh.jpg", fullName: "Lương Nhật Anh", dob: "18/11/2010" },
    "baongan": { displayName: "Bảo Ngân", img: "/assets/images/baongan.jpg", fullName: "Trần Bảo Ngân", dob: "25/07/2010" },
    "yennhi": { displayName: "Yến Nhi", img: "/assets/images/yennhi.jpg", fullName: "Tạ Yến Nhi", dob: "15/11/2010" },
    "lehuy": { displayName: "Lê Huy", img: "/assets/images/lehuy.jpg", fullName: "Lê Gia Huy", dob: "19/02/2010" },
    "baochau": { displayName: "Bảo Châu", img: "/assets/images/baochau.jpg", role: "Lớp phó học tập-Lớp phó đời sống-Thủ quỹ", fullName: "Đinh Thị Bảo Châu", dob: "01/11/2010" },
    "baoanh": { displayName: "Bảo Anh", img: "/assets/images/baoanh.jpg", fullName: "Lương Trần Bảo Anh", dob: "07/08/2010" },
    "vupanh": { displayName: "Vũ P.Anh", img: "/assets/images/vpa.jpg", role: "Lớp Trưởng", fullName: "Vũ Phương Anh", dob: "28/08/2010" },
    "minhanh": { displayName: "Minh Anh", img: "/assets/images/minhanh.jpg", fullName: "Vũ Thị Minh Anh", dob: "23/11/2010" },
    "xuanthanh": { displayName: "Xuân Thành", img: "/assets/images/xt.jpg", fullName: "Nguyễn Xuân Thành", dob: "01/11/2010" },
    "haanh": { displayName: "Hà Anh", img: "/assets/images/haanh.jpg", fullName: "Đinh Hà Anh", dob: "14/06/2010" },
}
